### ISSUE TITLE
App crash button with three lines

### ISSUE THREAD

**Issue by V0ssi** [marcoM32/SeaMapDroid#13]
Hi,
I'm using the version v1.9.7. The app crashed when I push the menu button in the left part of the app (the button with the three horizontal lines). 
This happen every time.

**Comment by marcoM32** [comment]
Hello, can you provide me the logs of this issue? because on my devices this issue does not appear

**Comment by erniepb** [comment]
Hello, I have the same issue on a Samsung S7 with Android 8. Where can I find the log file?

**Comment by marcoM32** [comment]
You can download the following app to track the crash:

Logcat Reader (A simple app to view logs) - https://f-droid.org/app/com.dp.logcatapp

to see the full error is necessary enable the specific android permission by adb shell, please see the app instruction.

**Comment by mwlczk** [comment]
FATAL EXCEPTION: main
Process: org.seamapdroid, PID: 1660
java.lang.RuntimeException: Canvas: trying to draw too large(109077136bytes) bitmap.
	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
	at android.widget.ImageView.onDraw(ImageView.java:1380)
	at android.view.View.draw(View.java:19135)
	at android.view.View.updateDisplayListIfDirty(View.java:18085)
	at android.view.View.draw(View.java:18863)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4218)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4004)
	at android.view.View.draw(View.java:19138)
	at android.view.View.updateDisplayListIfDirty(View.java:18085)
	at android.view.View.draw(View.java:18863)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4218)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4004)
	at android.view.View.updateDisplayListIfDirty(View.java:18076)
	at android.view.View.draw(View.java:18863)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4218)
	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4477)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4004)
	at android.view.View.draw(View.java:19138)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3869)
	at android.view.View.updateDisplayListIfDirty(View.java:18085)
	at android.view.View.draw(View.java:18863)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4218)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4004)
	at android.view.View.draw(View.java:19138)
	at android.support.design.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:87)
	at android.view.View.updateDisplayListIfDirty(View.java:18085)
	at android.view.View.draw(View.java:18863)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4218)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4004)
	at android.view.View.draw(View.java:19138)
	at android.view.View.updateDisplayListIfDirty(View.java:18085)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4202)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4182)
	at android.view.View.updateDisplayListIfDirty(View.java:18044)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4202)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4182)
	at android.view.View.updateDisplayListIfDirty(View.java:18044)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4202)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4182)
	at android.view.View.updateDisplayListIfDirty(View.java:18044)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4202)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4182)
	at android.view.View.updateDisplayListIfDirty(View.java:18044)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4202)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4182)
	at android.view.View.updateDisplayListIfDirty(View.java:18044)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3008)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2822)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2375)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1414)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6827)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)

**Comment by mwlczk** [comment]
And directly after this:
  Force finishing activity org.seamapdroid/.MainActivity

**Comment by mwlczk** [comment]
Showing crash dialog for package org.seamapdroid u0

**Comment by mwlczk** [comment]
@marcoM32 you need any more details?

**Comment by marcoM32** [comment]
Thanks @mwlczk for the report, I will try to fix the bug as soon as possible!!!

**Comment by marcoM32** [comment]
This error it should be resolved with the last version (v1.9.8) which will be available on F-Droid in the coming days.

**Comment by mwlczk** [comment]
Burger menu is replaced by dots. No crashes so far anymore. Thank you!
